name: Deploy static content to Pages

on:
  push:
    branches: [ version ]

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build
        run: |
          echo "$(echo `(cat app_rules.json)` | grep -o '"appRulesVersion": [0-9]*' | grep -o '[0-9]*')" > app_rules_version
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: xiaowine/Lyric-Getter
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
